{% set name = "rdflib-jsonld" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4f7d55326405071c7bce9acf5484643bcb984eadb84a6503053367da207105ed

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - rdflib >=4.2
    - setuptools

test:
  imports:
    - rdflib_jsonld

about:
  home: https://github.com/RDFLib/rdflib-jsonld
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: rdflib extension adding JSON-LD parser and serializer
  dev_url: https://github.com/RDFLib/rdflib-jsonld

extra:
  recipe-maintainers:
    - croth1
