# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 0.6.1

package:
  name: rdflib-jsonld
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/rdflib-jsonld/rdflib-jsonld-${{ version }}.tar.gz
  sha256: eda5a42a2e09f80d4da78e32b5c684bccdf275368f1541e6b7bcddfb1382a0e0

build:
  number: 1
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - wheel
  run:
    - python >=${{ python_min }}
    - rdflib >=5.0.0

tests:
  - python:
      imports: rdflib_jsonld
      pip_check: false
      python_version:
        - ${{ python_min }}.*
        - 3.13.*

about:
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: rdflib extension adding JSON-LD parser and serializer
  homepage: https://github.com/RDFLib/rdflib-jsonld
  repository: https://github.com/RDFLib/rdflib-jsonld

extra:
  recipe-maintainers:
    - croth1
    - bollwyvl
